global: #프로메테우스가 데이터를 가져가는 주기
  scrape_interval: 10s  # 20~60초
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]

  # Spring Boot 앱 (HikariCP 메트릭 포함)
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          application: 'my_api'

  # PostgreSQL 모니터링
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]
        labels:
          application: 'my_api'